// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Account
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public int Role { get; set; }

    public virtual ICollection<Subject> SubjectNavigation { get; set; } = new List<Subject>();

    public virtual ICollection<Test> Test { get; set; } = new List<Test>();

    public virtual ICollection<TestInstance> TestInstance { get; set; } = new List<TestInstance>();

    public virtual ICollection<Subject> Subject { get; set; } = new List<Subject>();
}