// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Options
{
    public int Id { get; set; }

    public bool SingleSelect { get; set; }

    public virtual ICollection<OptionAnswer> OptionAnswer { get; set; } = new List<OptionAnswer>();

    public virtual ICollection<Task> Task { get; set; } = new List<Task>();
}