// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class OptionAnswer
{
    public int Id { get; set; }

    public string Content { get; set; }

    public bool Correct { get; set; }

    public int OptionId { get; set; }

    public virtual Option Option { get; set; }
}