// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Subject
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int TeacherId { get; set; }

    public virtual Account Teacher { get; set; }

    public virtual ICollection<Test> Test { get; set; } = new List<Test>();

    public virtual ICollection<Account> Student { get; set; } = new List<Account>();
}