// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Task
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public int Type { get; set; }

    public int? OptionsId { get; set; }

    public virtual Options Options { get; set; }

    public virtual ICollection<TaskInstance> TaskInstance { get; set; } = new List<TaskInstance>();

    public virtual ICollection<Test> Test { get; set; } = new List<Test>();
}