// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class TaskInstance
{
    public int Id { get; set; }

    public string StudentAnswer { get; set; }

    public bool Correct { get; set; }

    public bool Checked { get; set; }

    public int TaskId { get; set; }

    public int TestInstanceId { get; set; }

    public virtual Task Task { get; set; }

    public virtual TestInstance TestInstance { get; set; }
}