// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class TestInstanceBase
{
    public int Id { get; set; }

    public int InstancesCount { get; set; }

    public bool Active { get; set; }

    public int TestId { get; set; }

    public virtual Test Test { get; set; }

    public virtual ICollection<TestInstance> TestInstance { get; set; } = new List<TestInstance>();
}