// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Test
{
    public int Id { get; set; }

    public string Name { get; set; }

    public TimeSpan Duration { get; set; }

    public string Description { get; set; }

    public int SubjectId { get; set; }

    public int TeacherId { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual Account Teacher { get; set; }

    public virtual ICollection<TestInstanceBase> TestInstanceBase { get; set; } = new List<TestInstanceBase>();

    public virtual ICollection<TestTask> TestTask { get; set; } = new List<TestTask>();
}