// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class Test
{
    public int Id { get; set; }

    public int Duration { get; set; }

    public string Description { get; set; }

    public int SubjectId { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual ICollection<TestInstance> TestInstances { get; set; } = new List<TestInstance>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}