// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class TestInstance
{
    public int Id { get; set; }

    public string InviteCode { get; set; }

    public bool Opened { get; set; }

    public int ElapsedTime { get; set; }

    public int TestId { get; set; }

    public int StudentId { get; set; }

    public virtual Account Student { get; set; }

    public virtual ICollection<TaskInstance> TaskInstances { get; set; } = new List<TaskInstance>();

    public virtual Test Test { get; set; }
}