// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeoQuest.Models;

public partial class TestTask
{
    public int Id { get; set; }

    public string MapType { get; set; }

    public string MapCenter { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public int Type { get; set; }

    public int? OptionsId { get; set; }

    public int TestId { get; set; }

    public virtual Options Options { get; set; }

    public virtual Test Test { get; set; }

    public virtual ICollection<TestTaskInstance> TestTaskInstance { get; set; } = new List<TestTaskInstance>();
}